services:
  app:
    image: ttl.sh/cypherrazzor-cfw-staging:24h
    restart: unless-stopped
    networks:
      - coolify
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0

networks:
  coolify:
    external: true
    name: coolify
