services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - coolify
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    labels:
      caddy: duahe1wymadv6xe2in3xh6vd.moncala.digitalesgeschaeft.de
      caddy.reverse_proxy: "{{upstreams 3000}}"

networks:
  coolify:
    external: true
    name: coolify
